version: "3.3"

services:
  finml:
    image: finml
    build: .
    volumes:
      - ./finml:/finml
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - postgres
    command: sh ./scripts/run.sh

  celery:
    image: finml
    volumes:
      - ./finml:/finml
    depends_on:
      - finml
      - redis
    env_file: .env
    command: python3 -m config.celery worker --loglevel debug

  celery_beat:
    image: finml
    volumes:
      - ./finml:/finml
    depends_on:
      - finml
      - redis
    env_file: .env
    command: python3 -m config.celery beat --loglevel=debug

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379

  postgres:
    image: postgres:11
    env_file: .env
    ports:
        - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
