version: "3.7"

services:
  finml:
    build: .
    volumes:
      - ./FinML:/FinML
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - postgres
    command: sh ./scripts/run.sh

  celery:
    build: .
    volumes:
      - ./FinML:/FinML
    depends_on:
      - finml
      - redis
    env_file: .env
    command: python3 -m config.celery worker --loglevel debug

  celery_beat:
    build: .
    volumes:
      - ./FinML:/FinML
    depends_on:
      - finml
      - redis
    env_file: .env
    command: python3 -m config.celery beat --loglevel=debug

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379

  postgres:
    image: postgres:12.2
    env_file: .env
    ports:
        - 5432:5432
    # volumes:
    #   - ./data:/var/lib/postgresql/data
