version: "3.7"

services:
  finml:
    build: .
    volumes:
      - ./finml:/finml
    command: python3 -m config.running

  celery:
    build: .
    volumes:
      - ./finml:/finml
    depends_on:
      - finml
      - redis
    command: python3 -m finml.celery -A finml worker
  
  rabbitmq:
    image: rabbitmq:3.7.8

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]

  database:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./database:/var/lib/postgresql/data
