version: "3.3"

services:
  finml:
    image: localhost:5000/finml/finml:latest
    volumes:
      - ./finml/src:/finml
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - postgres
    command: sh /home/run.sh

  celery:
    image: localhost:5000/finml/finml:latest
    volumes:
      - ./finml/src:/finml
    depends_on:
      - finml
      - redis
    env_file: .env
    command: python3 -m config.celery worker --loglevel debug

  celery1:
    image: localhost:5000/finml-finml:latest
    volumes:
      - ./finml/src:/finml
    depends_on:
      - finml
      - redis
    env_file: .env
    command: python3 -m config.celery worker --loglevel debug

  celery_beat:
    image: localhost:5000/finml/finml:latest
    volumes:
      - ./finml/src:/finml
    depends_on:
      - finml
      - redis
    env_file: .env
    command: python3 -m config.celery beat --loglevel=debug

  jupyterhub:
    image: localhost:5000/finml/jupyterhub:latest
    container_name: jupyterhub_hub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jupyterhub_data:/srv/jupyterhub
      - ./JupyterHub/jupyterhub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
    env_file: .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jupyterhub.rule=PathPrefix(`/`)"

  reverse-proxy:
    image: traefik:2.1.9
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/certs:/etc/certs
    command: --providers.docker=true --api.insecure=true

  jupyterlab:
    image: localhost:5000/finml/jupyterlab:latest
    container_name: jupyterlab
    command: echo

  redis:
    image: redis:alpine
    container_name: redis

  postgres:
    image: postgres:11
    env_file: .env
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
  jupyterhub_data:
