version: "3.3"

services:
  finml:
    image: finml
    build: ./finml
    volumes:
      - ./finml/src:/finml
    env_file: .env-sample
    ports:
      - 8000:8000
    depends_on:
      - postgres
    command: sh /home/run.sh

  celery:
    image: finml
    volumes:
      - ./finml/src:/finml
    depends_on:
      - finml
      - redis
    env_file: .env-sample
    command: python3 -m config.celery worker --loglevel debug

  celery_beat:
    image: finml
    volumes:
      - ./finml/src:/finml
    depends_on:
      - finml
      - redis
    env_file: .env-sample
    command: python3 -m config.celery beat --loglevel=debug

  jupyterlab:
    image: jupyterlab
    build: ./JupyterHub/jupyterlab
    container_name: jupyterlab
    ports:
      - 8888:8888

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379

  postgres:
    image: postgres:11
    env_file: .env
    ports:
        - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
  jupyterhub_data:
