# Generated by Django 3.0.7 on 2020-07-02 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquityIndex',
            fields=[
                ('name', models.CharField(help_text='Equity Name', max_length=40)),
                ('ticker', models.CharField(help_text='Equity Ticker Symbol', max_length=6, primary_key=True, serialize=False)),
                ('sector', models.CharField(blank=True, help_text='Equity Sector', max_length=40, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('query', models.BooleanField(default=True)),
                ('own', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OpenClose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('open', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.EquityIndex')),
            ],
        ),
        migrations.CreateModel(
            name='IntraDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('peratio', models.FloatField(blank=True, null=True)),
                ('bid', models.FloatField(blank=True, null=True)),
                ('ask', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, help_text='Quote Source', max_length=25, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.EquityIndex')),
            ],
        ),
    ]
