# Generated by Django 3.0.4 on 2020-03-24 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquityIndex',
            fields=[
                ('name', models.CharField(help_text='Equity Name', max_length=20)),
                ('ticker', models.CharField(help_text='Equity Ticker Symbol', max_length=4, primary_key=True, serialize=False)),
                ('industry', models.CharField(blank=True, help_text='Equity Industry', max_length=20, null=True)),
                ('industry_2', models.CharField(blank=True, help_text='Equity Industry 2', max_length=20, null=True)),
                ('industry_3', models.CharField(blank=True, help_text='Equity Industry 3', max_length=20, null=True)),
                ('query', models.BooleanField(default=True)),
                ('own', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('bid', models.FloatField(blank=True, null=True)),
                ('ask', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField()),
                ('marketcap', models.IntegerField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.EquityIndex')),
            ],
        ),
    ]
