# Generated by Django 3.0.7 on 2020-07-01 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquityIndex',
            fields=[
                ('name', models.CharField(help_text='Equity Name', max_length=40)),
                ('ticker', models.CharField(help_text='Equity Ticker Symbol', max_length=6, primary_key=True, serialize=False)),
                ('industry', models.CharField(blank=True, help_text='Equity Industry', max_length=40, null=True)),
                ('currency', models.CharField(blank=True, help_text='Equity Currency', max_length=3, null=True)),
                ('exchange', models.CharField(blank=True, help_text='Equity Exchange', max_length=6, null=True)),
                ('query', models.BooleanField(default=True)),
                ('own', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('low', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.EquityIndex')),
            ],
        ),
    ]
